# Generated by Django 2.1.3 on 2018-11-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubelinks', '0003_auto_20181127_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubelink',
            options={'ordering': ('-timestamp', 'title')},
        ),
        migrations.AddField(
            model_name='youtubelink',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
